title: Nolboo's Blog

# Oveerriden by GitHub Pages: https://help.github.com/articles/using-jekyll-with-pages#configuring-jekyll
safe: true
highlighter: pygments
lsi: false

permalink: pretty

markdown:     redcarpet

redcarpet:
    extensions: 
      - no_intra_emphasis
      - fenced_code_blocks
      - tables
      - strikethrough
      - superscript
      - autolink
      - hard_wrap

# redcarpet:
#    extensions: ["smart"]

gems:
  - jemoji

paginate: 10

author:
    twitter: n0lb00
    github: nolboo